version: "3.9"

services:
  wordpress:
    container_name: wordpress_prod
    image: wordpress:6.8.3-php8.3-fpm
    restart: always
    env_file:
      - ./env/.env.production
    networks:
      - wordpress_prod_net
    volumes:
      - ../src:/var/www/html
      - ../src/wp-content/themes:/var/www/html/wp-content/themes
      - ../src/wp-content/plugins:/var/www/html/wp-content/plugins
      - wordpress_prod_uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql

  mysql:
    container_name: mysql_prod
    image: mysql:8.0
    restart: always
    env_file:
      - ./env/.env.production
    networks:
      - wordpress_prod_net
    volumes:
      - db_prod_data:/var/lib/mysql
      - ../database/db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  nginx:
    container_name: nginx_prod
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/var/www/html
      - ../src/wp-content/themes:/var/www/html/wp-content/themes
      - ../src/wp-content/plugins:/var/www/html/wp-content/plugins
      - wordpress_prod_uploads:/var/www/html/wp-content/uploads
      - ./nginx/production.conf:/etc/nginx/conf.d/default.conf
      - certbot_prod_etc:/etc/letsencrypt
      - certbot_prod_var:/var/lib/letsencrypt
      - certbot_prod_www:/var/www/certbot
    networks:
      - wordpress_prod_net
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_prod
    volumes:
      - certbot_prod_etc:/etc/letsencrypt
      - certbot_prod_var:/var/lib/letsencrypt
      - certbot_prod_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - wordpress_prod_net

networks:
  wordpress_prod_net:

volumes:
  wordpress_prod_uploads:
  db_prod_data:
  certbot_prod_etc:
  certbot_prod_var:
  certbot_prod_www:
