version: "3.8"

services:
  wordpress:
    container_name: wordpress_staging
    image: wordpress:6.8.3-php8.3-fpm
    restart: always
    env_file:
      - ./env/.env.staging
    networks:
      - wordpress_staging_net
    volumes:
      - ../src:/var/www/html
      - ../src/wp-content/themes:/var/www/html/wp-content/themes
      - ../src/wp-content/plugins:/var/www/html/wp-content/plugins
      - wordpress_staging_uploads:/var/www/html/wp-content/uploads
    depends_on:
      - mysql

  mysql:
    container_name: mysql_staging
    image: mysql:8.0
    restart: always
    env_file:
      - ./env/.env.staging
    networks:
      - wordpress_staging_net
    volumes:
      - db_staging_data:/var/lib/mysql
      - ../database/db.sql:/docker-entrypoint-initdb.d/db.sql:ro

  nginx:
    container_name: nginx_staging
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../src:/var/www/html
      - ../src/wp-content/themes:/var/www/html/wp-content/themes
      - ../src/wp-content/plugins:/var/www/html/wp-content/plugins
      - wordpress_staging_uploads:/var/www/html/wp-content/uploads
      - ./nginx/staging.conf:/etc/nginx/conf.d/default.conf
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - wordpress_staging_net
    depends_on:
      - wordpress

  certbot:
    image: certbot/certbot:latest
    container_name: certbot_staging
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
    command: certonly --manual --preferred-challenges dns --email binh.vu@mikotech.vn --agree-tos --no-eff-email --staging -d binhdi.io.vn
    stdin_open: true
    tty: true

networks:
  wordpress_staging_net:

volumes:
  wordpress_staging_uploads:
  db_staging_data:
  certbot_etc:
  certbot_var:
  certbot_www:
